# -*- coding: utf-8 -*-
"""chrome city through D&D

Revision ID: 4d1e6fc4e9dd
Revises: 526b3613c98f
Create Date: 2016-01-30 13:06:41.968700

"""

# revision identifiers, used by Alembic.
revision = '4d1e6fc4e9dd'
down_revision = '526b3613c98f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    card = sa.sql.table(
        'card',
        sa.sql.column('file_name'),
        sa.sql.column('card_name'))

    op.bulk_insert(card, [
        {"card_name": "Immolation Script", "file_name": "08041.png"},
        {"card_name": "Skulljack", "file_name": "08042.png"},
        {"card_name": "Turntable", "file_name": "08043.png"},
        {"card_name": "Chrome Parlor", "file_name": "08044.png"},
        {"card_name": "Titanium Ribs", "file_name": "08045.png"},
        {"card_name": "Crowbar", "file_name": "08046.png"},
        {"card_name": "Net-Ready Eyes", "file_name": "08047.png"},
        {"card_name": "Analog Dreamers", "file_name": "08048.png"},
        {"card_name": "Brain Cage", "file_name": "08049.png"},
        {"card_name": "Cybernetics Division: Humanity Upgraded", "file_name": "08050.png"},
        {"card_name": "Self-Destruct Chips", "file_name": "08051.png"},
        {"card_name": "Lab Dog", "file_name": "08052.png"},
        {"card_name": "Oaktown Grid", "file_name": "08053.png"},
        {"card_name": "Ryon Knight", "file_name": "08054.png"},
        {"card_name": "Clairvoyant Monitor", "file_name": "08055.png"},
        {"card_name": "Lockdown", "file_name": "08056.png"},
        {"card_name": "Little Engine", "file_name": "08057.png"},
        {"card_name": "Oaktown Renovation", "file_name": "08058.png"},
        {"card_name": "Corporate Town", "file_name": "08059.png"},
        {"card_name": "Quicksand", "file_name": "08060.png"},
        {"card_name": "Faust", "file_name": "08061.png"},
        {"card_name": "Street Peddler", "file_name": "08062.png"},
        {"card_name": 'Armand "Geist" Walker: Tech Lord', "file_name": "08063.png"},
        {"card_name": "Drive By", "file_name": "08064.png"},
        {"card_name": "Forger", "file_name": "08065.png"},
        {"card_name": "Shiv", "file_name": "08066.png"},
        {"card_name": "Gang Sign", "file_name": "08067.png"},
        {"card_name": "Muertos Gang Member", "file_name": "08068.png"},
        {"card_name": "Chameleon", "file_name": "08069.png"},
        {"card_name": "Hyperdriver", "file_name": "08070.png"},
        {"card_name": "Test Ground", "file_name": "08071.png"},
        {"card_name": "Defective Brainchips", "file_name": "08072.png"},
        {"card_name": "Allele Repression", "file_name": "08073.png"},
        {"card_name": "Marcus Batty", "file_name": "08074.png"},
        {"card_name": "Exposé".decode('utf-8'), "file_name": "08075.png"},
        {"card_name": "Pachinko", "file_name": "08076.png"},
        {"card_name": "Underway Renovation", "file_name": "08077.png"},
        {"card_name": "Contract Killer", "file_name": "08078.png"},
        {"card_name": "Spiderweb", "file_name": "08079.png"},
        {"card_name": "Underway Grid", "file_name": "08080.png"},
        {"card_name": "Trope", "file_name": "08081.png"},
        {"card_name": "Spoilers", "file_name": "08082.png"},
        {"card_name": "Drug Dealer", "file_name": "08083.png"},
        {"card_name": "Rolodex", "file_name": "08084.png"},
        {"card_name": "Fan Site", "file_name": "08085.png"},
        {"card_name": "Film Critic", "file_name": "08086.png"},
        {"card_name": "Paparazzi", "file_name": "08087.png"},
        {"card_name": "Ronald Five", "file_name": "08088.png"},
        {"card_name": "Enforcer 1.0", "file_name": "08089.png"},
        {"card_name": "It's a Trap!", "file_name": "08090.png"},
        {"card_name": "An Offer You Can't Refuse", "file_name": "08091.png"},
        {"card_name": "Haarpsichord Studios: Entertainment Unleashed", "file_name": "08092.png"},
        {"card_name": "Award Bait", "file_name": "08093.png"},
        {"card_name": "Explode-a-palooza", "file_name": "08094.png"},
        {"card_name": "Early Premiere", "file_name": "08095.png"},
        {"card_name": "Casting Call", "file_name": "08096.png"},
        {"card_name": "Old Hollywood Grid", "file_name": "08097.png"},
        {"card_name": "Hollywood Renovation", "file_name": "08098.png"},
        {"card_name": "Back Channels", "file_name": "08099.png"},
        {"card_name": "Vanity Project", "file_name": "08100.png"},
        {"card_name": "Power to the People", "file_name": "08101.png"},
        {"card_name": "Surfer", "file_name": "08102.png"},
        {"card_name": "DDoS", "file_name": "08103.png"},
        {"card_name": "Laramy Fisk: Savvy Investor", "file_name": "08104.png"},
        {"card_name": "Fisk Investment Seminar", "file_name": "08105.png"},
        {"card_name": "Bookmark", "file_name": "08106.png"},
        {"card_name": "DaVinci", "file_name": "08107.png"},
        {"card_name": "Wireless Net Pavilion", "file_name": "08108.png"},
        {"card_name": "Cybernetics Court", "file_name": "08109.png"},
        {"card_name": "Team Sponsorship", "file_name": "08110.png"},
        {"card_name": "Chronos Protocol: Selective Mind-mapping", "file_name": "08111.png"},
        {"card_name": "Ancestral Imager", "file_name": "08112.png"},
        {"card_name": "Genetics Pavilion", "file_name": "08113.png"},
        {"card_name": "Franchise City", "file_name": "08114.png"},
        {"card_name": "Product Placement", "file_name": "08115.png"},
        {"card_name": "Worlds Plaza", "file_name": "08116.png"},
        {"card_name": "Public Support", "file_name": "08117.png"},
        {"card_name": "Tour Guide", "file_name": "08118.png"},
        {"card_name": "Expo Grid", "file_name": "08119.png"},
        {"card_name": "The Future is Now", "file_name": "08120.png"},
        {"card_name": "SYNC: Everything, Everywhere", "file_name": "09001.png"},
        {"card_name": "New Angeles Sol: Your News", "file_name": "09002.png"},
        {"card_name": "Spark Agency: Worldswide Reach", "file_name": "09003.png"},
        {"card_name": "15 Minutes", "file_name": "09004.png"},
        {"card_name": "Improved Tracers", "file_name": "09005.png"},
        {"card_name": "Rebranding Team", "file_name": "09006.png"},
        {"card_name": "Quantum Predictive Model", "file_name": "09007.png"},
        {"card_name": "Lily Lockwell", "file_name": "09008.png"},
        {"card_name": "News Team", "file_name": "09009.png"},
        {"card_name": "Shannon Claire", "file_name": "09010.png"},
        {"card_name": "Victoria Jenkins", "file_name": "09011.png"},
        {"card_name": "Reality Threedee", "file_name": "09012.png"},
        {"card_name": "Archangel", "file_name": "09013.png"},
        {"card_name": "News Hound", "file_name": "09014.png"},
        {"card_name": "Resistor", "file_name": "09015.png"},
        {"card_name": "Special Offer", "file_name": "09016.png"},
        {"card_name": "TL;DR", "file_name": "09017.png"},
        {"card_name": "Turnpike", "file_name": "09018.png"},
        {"card_name": "24/7 News Cycle", "file_name": "09019.png"},
        {"card_name": "Ad Blitz", "file_name": "09020.png"},
        {"card_name": "Media Blitz", "file_name": "09021.png"},
        {"card_name": "The All-Seeing I", "file_name": "09022.png"},
        {"card_name": "Surveillance Sweep", "file_name": "09023.png"},
        {"card_name": "Keegan Lane", "file_name": "09024.png"},
        {"card_name": "Rutherford Grid", "file_name": "09025.png"},
        {"card_name": "Global Food Initiative", "file_name": "09026.png"},
        {"card_name": "Launch Campaign", "file_name": "09027.png"},
        {"card_name": "Assassin", "file_name": "09028.png"},
        {"card_name": "Apex: Invasive Predator", "file_name": "09029.png"},
        {"card_name": "Apocalypse", "file_name": "09030.png"},
        {"card_name": "Prey", "file_name": "09031.png"},
        {"card_name": "Heartbeat", "file_name": "09032.png"},
        {"card_name": "Endless Hunger", "file_name": "09033.png"},
        {"card_name": "Harbinger", "file_name": "09034.png"},
        {"card_name": "Hunting Grounds", "file_name": "09035.png"},
        {"card_name": "Wasteland", "file_name": "09036.png"},
        {"card_name": "Adam: Compulsive Hacker", "file_name": "09037.png"},
        {"card_name": "Independent Thinking", "file_name": "09038.png"},
        {"card_name": "Brain Chip", "file_name": "09039.png"},
        {"card_name": "Multithreader", "file_name": "09040.png"},
        {"card_name": "Always Be Running", "file_name": "09041.png"},
        {"card_name": "Dr. Lovegood", "file_name": "09042.png"},
        {"card_name": "Neutralize All Threats", "file_name": "09043.png"},
        {"card_name": "Safety First", "file_name": "09044.png"},
        {"card_name": "Sunny Lebeau: Security Specialist", "file_name": "09045.png"},
        {"card_name": "Security Chip", "file_name": "09046.png"},
        {"card_name": "Security Nexus", "file_name": "09047.png"},
        {"card_name": "GS Striker M1", "file_name": "09048.png"},
        {"card_name": "GS Shrike M2", "file_name": "09049.png"},
        {"card_name": "GS Sherman M3", "file_name": "09050.png"},
        {"card_name": "Globalsec Security Clearance", "file_name": "09051.png"},
        {"card_name": "Jak Sinclair", "file_name": "09052.png"},
        {"card_name": "Employee Strike", "file_name": "09053.png"},
        {"card_name": "Windfall", "file_name": "09054.png"},
        {"card_name": "Technical Writer", "file_name": "09055.png"},
        {"card_name": "Run Amok", "file_name": "10001.png"},
        {"card_name": "Ramujan-reliant 550 BMI", "file_name": "10002.png"},
        {"card_name": "Street Magic", "file_name": "10003.png"},
        {"card_name": "High-stakes Job", "file_name": "10004.png"},
        {"card_name": "Mongoose", "file_name": "10005.png"},
        {"card_name": "Jesminder Sareen: Girl Behind the Curtain", "file_name": "10006.png"},
        {"card_name": "Maya", "file_name": "10007.png"},
        {"card_name": "Panchatantra", "file_name": "10008.png"},
        {"card_name": "Artist Colony", "file_name": "10009.png"},
        {"card_name": "Chatterjee University", "file_name": "10010.png"},
        {"card_name": "Advanced Concept Hopper", "file_name": "10011.png"},
        {"card_name": "Vikram 1.0", "file_name": "10012.png"},
        {"card_name": "Heritage Committee", "file_name": "10013.png"},
        {"card_name": "Mumbad City Grid", "file_name": "10014.png"},
        {"card_name": "Kala Ghoda Real TV", "file_name": "10015.png"},
        {"card_name": "Interrupt 0", "file_name": "10016.png"},
        {"card_name": "Dedication Ceremony", "file_name": "10017.png"},
        {"card_name": "Mumba Temple", "file_name": "10018.png"},
        {"card_name": "Museum of History", "file_name": "10019.png"}
    ])

def downgrade():
    pass
