"""inital card inserts

Revision ID: 14e9d429af5
Revises:
Create Date: 2015-03-21 10:05:07.911516

"""

# revision identifiers, used by Alembic.
revision = '14e9d429af5'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    card = op.create_table(
        'card',
        sa.Column('file_name', sa.String(100), primary_key=True, nullable=False),
        sa.Column('card_name', sa.String(100), nullable=False)
    )

    op.bulk_insert(card, [
        {"file_name": "accelerated-beta-test.png", "card_name": "Accelerated Beta Test"},
        {"file_name": "accelerated-diagnostics.png", "card_name": "Accelerated Diagnostics"},
        {"file_name": "access-to-globalsec.png", "card_name": "Access to Globalsec"},
        {"file_name": "account-siphon.png", "card_name": "Account Siphon"},
        {"file_name": "activist-support.png", "card_name": "Activist Support"},
        {"file_name": "adonis-campaign.png", "card_name": "Adonis Campaign"},
        {"file_name": "aesops-pawnshop.png", "card_name": "Aesop's Pawnshop"},
        {"file_name": "aggressive-negotiation.png", "card_name": "Aggressive Negotiation"},
        {"file_name": "aggressive-secretary.png", "card_name": "Aggressive Secretary"},
        {"file_name": "akamatsu-mem-chip.png", "card_name": "Akamatsu Mem Chip"},
        {"file_name": "akitaro-watanabe.png", "card_name": "Akitaro Watanabe"},
        {"file_name": "alias.png", "card_name": "Alias"},
        {"file_name": "alix-t4lb07.png", "card_name": "Alix T4LB07"},
        {"file_name": "all-nighter.png", "card_name": "All-nighter"},
        {"file_name": "alpha.png", "card_name": "Alpha"},
        {"file_name": "amazon-industrial-zone.png", "card_name": "Amazon Industrial Zone"},
        {"file_name": "amped-up.png", "card_name": "Amped Up"},
        {"file_name": "angel-arena.png", "card_name": "Angel Arena"},
        {"file_name": "anonymous-tip.png", "card_name": "Anonymous Tip"},
        {"file_name": "archer.png", "card_name": "Archer"},
        {"file_name": "architect.png", "card_name": "Architect"},
        {"file_name": "archived-memories.png", "card_name": "Archived Memories"},
        {"file_name": "archives-interface.png", "card_name": "Archives Interface"},
        {"file_name": "armitage-codebusting.png", "card_name": "Armitage Codebusting"},
        {"file_name": "ashigaru.png", "card_name": "Ashigaru"},
        {"file_name": "asteroid-belt.png", "card_name": "Asteroid Belt"},
        {"file_name": "astrolabe.png", "card_name": "Astrolabe"},
        {"file_name": "astroscript-pilot-program.png", "card_name": "AstroScript Pilot Program"},
        {"file_name": "atman.png", "card_name": "Atman"},
        {"file_name": "au-revoir.png", "card_name": "Au Revoir"},
        {"file_name": "aurora.png", "card_name": "Aurora"},
        {"file_name": "autoscripter.png", "card_name": "Autoscripter"},
        {"file_name": "awakening-center.png", "card_name": "Awakening Center"},
        {"file_name": "bad-times.png", "card_name": "Bad Times"},
        {"file_name": "bank-job.png", "card_name": "Bank Job"},
        {"file_name": "bastion.png", "card_name": "Bastion"},
        {"file_name": "battering-ram.png", "card_name": "Battering Ram"},
        {"file_name": "beanstalk-royalties.png", "card_name": "Beanstalk Royalties"},
        {"file_name": "bernice-mai.png", "card_name": "Bernice Mai"},
        {"file_name": "big-brother.png", "card_name": "Big Brother"},
        {"file_name": "bioroid-efficiency-research.png", "card_name": "Bioroid Efficiency Research"},
        {"file_name": "biotic-labor.png", "card_name": "Biotic Labor"},
        {"file_name": "bishop.png", "card_name": "Bishop"},
        {"file_name": "bitfrost-array.png", "card_name": "Bifrost Array"},
        {"file_name": "blackat.png", "card_name": "BlacKat"},
        {"file_name": "blackguard.png", "card_name": "Blackguard"},
        {"file_name": "blackmail.png", "card_name": "Blackmail"},
        {"file_name": "blue-level-clearance.png", "card_name": "Blue Level Clearance"},
        {"file_name": "borrowed-satellite.png", "card_name": "Borrowed Satellite"},
        {"file_name": "box-e.png", "card_name": "Box-E"},
        {"file_name": "braintrust.png", "card_name": "Braintrust"},
        {"file_name": "breach.png", "card_name": "Breach"},
        {"file_name": "breaking-news.png", "card_name": "Breaking News"},
        {"file_name": "bribery.png", "card_name": "Bribery"},
        {"file_name": "broadcast-square.png", "card_name": "Broadcast Square"},
        {"file_name": "bug.png", "card_name": "Bug"},
        {"file_name": "builder.png", "card_name": "Builder"},
        {"file_name": "bullfrog.png", "card_name": "Bullfrog"},
        {"file_name": "burke-bugs.png", "card_name": "Burke Bugs"},
        {"file_name": "cache.png", "card_name": "Cache"},
        {"file_name": "caduceus.png", "card_name": "Caduceus"},
        {"file_name": "calling-in-favors.png", "card_name": "Calling in Favors"},
        {"file_name": "caprice-nisei.png", "card_name": "Caprice Nisei"},
        {"file_name": "capstone.png", "card_name": "Capstone"},
        {"file_name": "celebrity-gift.png", "card_name": "Celebrity Gift"},
        {"file_name": "cell-portal.png", "card_name": "Cell Portal"},
        {"file_name": "cerberus-lady-h1.png", "card_name": "Cerberus 'Lady' H1"},
        {"file_name": "cerberus-rex-h2.png", "card_name": "Cerberus 'Rex' H2"},
        {"file_name": "cerebral-cast.png", "card_name": "Cerebral Cast"},
        {"file_name": "cerebral-imaging-infinite-frontiers.png", "card_name": "Cerebral Imaging: Infinite Frontiers"},
        {"file_name": "cerebral-overwriter.png", "card_name": "Cerebral Overwriter"},
        {"file_name": "cerebral-static.png", "card_name": "Cerebral Static"},
        {"file_name": "chairman-hiro.png", "card_name": "Chairman Hiro"},
        {"file_name": "chakana.png", "card_name": "Chakana"},
        {"file_name": "changeling.png", "card_name": "Changeling"},
        {"file_name": "character-assassination.png", "card_name": "Character Assassination"},
        {"file_name": "checkpoint.png", "card_name": "Checkpoint"},
        {"file_name": "chilo-city-grid.png", "card_name": "ChiLo City Grid"},
        {"file_name": "chimera.png", "card_name": "Chimera"},
        {"file_name": "chop-bot-3000.png", "card_name": "Chop Bot 3000"},
        {"file_name": "chronos-project.png", "card_name": "Chronos Project"},
        {"file_name": "chum.png", "card_name": "Chum"},
        {"file_name": "city-surveillance.png", "card_name": "City Surveillance"},
        {"file_name": "cloak.png", "card_name": "Cloak"},
        {"file_name": "clone-chip.png", "card_name": "Clone Chip"},
        {"file_name": "clone-retirement.png", "card_name": "Clone Retirement"},
        {"file_name": "closed-accounts.png", "card_name": "Closed Accounts"},
        {"file_name": "code-siphon.png", "card_name": "Code Siphon"},
        {"file_name": "collective-consciousness.png", "card_name": "Collective Consciousness"},
        {"file_name": "commercialization.png", "card_name": "Commercialization"},
        {"file_name": "compromised-employee.png", "card_name": "Compromised Employee"},
        {"file_name": "contellation-protocol.png", "card_name": "Constellation Protocol"},
        {"file_name": "copycat.png", "card_name": "Copycat"},
        {"file_name": "corporate-shuffle.png", "card_name": "Corporate Shuffle"},
        {"file_name": "corporate-troubleshooter.png", "card_name": "Corporate Troubleshooter"},
        {"file_name": "corporate-war.png", "card_name": "Corporate War"},
        {"file_name": "corroder.png", "card_name": "Corroder"},
        {"file_name": "cortez-chip.png", "card_name": "Cortez Chip"},
        {"file_name": "crash-space.png", "card_name": "Crash Space"},
        {"file_name": "creeper.png", "card_name": "Creeper"},
        {"file_name": "crescentus.png", "card_name": "Crescentus"},
        {"file_name": "crisium-grid.png", "card_name": "Crisium Grid"},
        {"file_name": "crypsis.png", "card_name": "Crypsis"},
        {"file_name": "curtain-wall.png", "card_name": "Curtain Wall"},
        {"file_name": "custom-biotics-engineered-for-success.png", "card_name": "Custom Biotics: Engineered for Success"},
        {"file_name": "cyber-cypher.png", "card_name": "Cyber-Cypher"},
        {"file_name": "cyber-threat.png", "card_name": "Cyber Threat"},
        {"file_name": "cyberdex-trial.png", "card_name": "Cyberdex Trial"},
        {"file_name": "cyberdex-virus-suite.png", "card_name": "Cyberdex Virus Suite"},
        {"file_name": "cyberfeeder.png", "card_name": "Cyberfeeder"},
        {"file_name": "cybersoft-macrodrive.png", "card_name": "Cybsoft MacroDrive"},
        {"file_name": "cybersolutions-mem-chip.png", "card_name": "CyberSolutions Mem Chip"},
        {"file_name": "d4v1d.png", "card_name": "D4v1d"},
        {"file_name": "dagger.png", "card_name": "Dagger"},
        {"file_name": "daily-business-show.png", "card_name": "Daily Business Show"},
        {"file_name": "daily-casts.png", "card_name": "Daily Casts"},
        {"file_name": "darwin.png", "card_name": "Darwin"},
        {"file_name": "data-dealer.png", "card_name": "Data Dealer"},
        {"file_name": "data-folding.png", "card_name": "Data Folding"},
        {"file_name": "data-hound.png", "card_name": "Data Hound"},
        {"file_name": "data-leak-reversal.png", "card_name": "Data Leak Reversal"},
        {"file_name": "data-mine.png", "card_name": "Data Mine"},
        {"file_name": "data-raven.png", "card_name": "Data Raven"},
        {"file_name": "datapike.png", "card_name": "Datapike"},
        {"file_name": "datasucker.png", "card_name": "Datasucker"},
        {"file_name": "day-job.png", "card_name": "Day Job"},
        {"file_name": "decoy.png", "card_name": "Decoy"},
        {"file_name": "dedicated-response-team.png", "card_name": "Dedicated Response Team"},
        {"file_name": "dedicated-server.png", "card_name": "Dedicated Server"},
        {"file_name": "dedicated-technician-team.png", "card_name": "Dedicated Technician Team"},
        {"file_name": "deep-red.png", "card_name": "Deep Red"},
        {"file_name": "deep-thought.png", "card_name": "Deep Thought"},
        {"file_name": "demolition-run.png", "card_name": "Demolition Run"},
        {"file_name": "desperado.png", "card_name": "Desperado"},
        {"file_name": "deus-x.png", "card_name": "Caduceus"},
        {"file_name": "diesel.png", "card_name": "Diesel"},
        {"file_name": "dinosaurus.png", "card_name": "Dinosaurus"},
        {"file_name": "director-haas-pet-project.png", "card_name": "Director Haas' Pet Project"},
        {"file_name": "director-haas.png", "card_name": "Director Haas"},
        {"file_name": "dirty-laundry.png", "card_name": "Dirty Laundry"},
        {"file_name": "disrupter.png", "card_name": "Disrupter"},
        {"file_name": "diversified-portfolio.png", "card_name": "Diversified Portfolio"},
        {"file_name": "djinn.png", "card_name": "Djinn"},
        {"file_name": "domestic-sleepers.png", "card_name": "Domestic Sleepers"},
        {"file_name": "donut-taganes.png", "card_name": "Donut Taganes"},
        {"file_name": "doppelganger.png", "card_name": "Doppelgänger"},
        {"file_name": "draco.png", "card_name": "Dracō"},
        {"file_name": "duggars.png", "card_name": "Duggar's"},
        {"file_name": "dyson-fractal-generator.png", "card_name": "Dyson Fractal Generator"},
        {"file_name": "dyson-mem-chip.png", "card_name": "Dyson Mem Chip"},
        {"file_name": "e3-feedback-implants.png", "card_name": "e3 Feedback Implants"},
        {"file_name": "eak-efficiency.png", "card_name": "Peak Efficiency"},
        {"file_name": "early-bird.png", "card_name": "Early Bird"},
        {"file_name": "earthrise-hotel.png", "card_name": "Earthrise Hotel"},
        {"file_name": "easy-mark.png", "card_name": "Easy Mark"},
        {"file_name": "eater.png", "card_name": "Eater"},
        {"file_name": "eden-fragment.png", "card_name": "Eden Fragment"},
        {"file_name": "eden-shard.png", "card_name": "Eden Shard"},
        {"file_name": "edge-of-world.png", "card_name": "Edge of World"},
        {"file_name": "edward-kim.png", "card_name": "Swarm"},
        {"file_name": "efficiency-committee.png", "card_name": "Efficiency Committee"},
        {"file_name": "ekomind.png", "card_name": "Ekomind"},
        {"file_name": "eli-1-0.png", "card_name": "Eli 1.0"},
        {"file_name": "elizabeth-mills.png", "card_name": "Elizabeth Mills"},
        {"file_name": "elizas-toybox.png", "card_name": "Eliza's Toybox"},
        {"file_name": "emergency-shutdown.png", "card_name": "Emergency Shutdown"},
        {"file_name": "encrypted-portals.png", "card_name": "Encrypted Portals"},
        {"file_name": "encryption-protocol.png", "card_name": "Encryption Protocol"},
        {"file_name": "enhanced-login-protocol.png", "card_name": "Enhanced Login Protocol"},
        {"file_name": "enigma.png", "card_name": "Enigma"},
        {"file_name": "errand-boy.png", "card_name": "Errand Boy"},
        {"file_name": "escher.png", "card_name": "Escher"},
        {"file_name": "eureka.png", "card_name": "Eureka!"},
        {"file_name": "eve-campaign.png", "card_name": "Eve Campaign"},
        {"file_name": "excalibur.png", "card_name": "Excalibur"},
        {"file_name": "executive-boot-camp.png", "card_name": "Executive Boot Camp"},
        {"file_name": "executive-retreat.png", "card_name": "Executive Retreat"},
        {"file_name": "executive-wiretaps.png", "card_name": "Executive Wiretaps"},
        {"file_name": "exile-streethawk.png", "card_name": "Exile: Streethawk"},
        {"file_name": "experiential-data.png", "card_name": "Experiential Data"},
        {"file_name": "expert-schedule-analyzer.png", "card_name": "Expert Schedule Analyzer"},
        {"file_name": "exploratory-romp.png", "card_name": "Exploratory Romp"},
        {"file_name": "express-delivery.png", "card_name": "Express Delivery"},
        {"file_name": "faerie.png", "card_name": "Faerie"},
        {"file_name": "fall-guy.png", "card_name": "Fall Guy"},
        {"file_name": "false-echo.png", "card_name": "False Echo"},
        {"file_name": "false-lead.png", "card_name": "False Lead"},
        {"file_name": "fast-track.png", "card_name": "Fast Track"},
        {"file_name": "feedback-filter.png", "card_name": "Feedback Filter"},
        {"file_name": "feint.png", "card_name": "Feint"},
        {"file_name": "femme-fatale.png", "card_name": "Femme Fatale"},
        {"file_name": "fenris.png", "card_name": "Fenris"},
        {"file_name": "fester.png", "card_name": "Fester"},
        {"file_name": "fire-wall.png", "card_name": "Fire Wall"},
        {"file_name": "firmware-updates.png", "card_name": "Firmware Updates"},
        {"file_name": "flare.png", "card_name": "Flare"},
        {"file_name": "force-of-nature.png", "card_name": "Force of Nature"},
        {"file_name": "forged-activation-orders.png", "card_name": "Forged Activation Orders"},
        {"file_name": "forked.png", "card_name": "Forked"},
        {"file_name": "foxfire.png", "card_name": "Foxfire"},
        {"file_name": "frame-job.png", "card_name": "Frame Job"},
        {"file_name": "freelance-coding-contract.png", "card_name": "Freelance Coding Contract"},
        {"file_name": "freelancer.png", "card_name": "Freelancer"},
        {"file_name": "galahad.png", "card_name": "Galahad"},
        {"file_name": "garrote.png", "card_name": "Garrote"},
        {"file_name": "gemini.png", "card_name": "Gemini"},
        {"file_name": "geothermal-fracking.png", "card_name": "Geothermal Fracking"},
        {"file_name": "ghost-branch.png", "card_name": "Ghost Branch"},
        {"file_name": "ghost-runner.png", "card_name": "Ghost Runner"},
        {"file_name": "gila-hands-arcology.png", "card_name": "Gila Hands Arcology"},
        {"file_name": "gingerbread.png", "card_name": "Gingerbread"},
        {"file_name": "glenn-station.png", "card_name": "Glenn Station"},
        {"file_name": "gordian-blade.png", "card_name": "Gordian Blade"},
        {"file_name": "gorman-drip-v1.png", "card_name": "Gorman Drip v1"},
        {"file_name": "government-contracts.png", "card_name": "Government Contracts"},
        {"file_name": "government-takeover.png", "card_name": "Government Takeover"},
        {"file_name": "grappling-hook.png", "card_name": "Grappling Hook"},
        {"file_name": "gravedigger.png", "card_name": "Gravedigger"},
        {"file_name": "green-level-clearance.png", "card_name": "Green Level Clearance"},
        {"file_name": "grifter.png", "card_name": "Grifter"},
        {"file_name": "grim.png", "card_name": "Grim"},
        {"file_name": "grimoire.png", "card_name": "Grimoire"},
        {"file_name": "grndl-power-unleashed.png", "card_name": "GRNDL: Power Unleashed"},
        {"file_name": "guard.png", "card_name": "Guard"},
        {"file_name": "gyri-labyrinth.png", "card_name": "Gyri Labyrinth"},
        {"file_name": "haas-arcology-ai.png", "card_name": "Haas Arcology AI"},
        {"file_name": "haas-bioroid-stronger-together.png", "card_name": "Haas-Bioroid: Stronger Together"},
        {"file_name": "hades-fragment.png", "card_name": "Hades Fragment"},
        {"file_name": "hades-shard.png", "card_name": "Hades Shard"},
        {"file_name": "hadrians-wall.png", "card_name": "Hadrian's Wall"},
        {"file_name": "hard-at-work.png", "card_name": "Hard at Work"},
        {"file_name": "harmony-medtech-biomedical-pioneer.png", "card_name": "Harmony Medtech: Biomedical Pioneer"},
        {"file_name": "hedge-fund.png", "card_name": "Hedge Fund"},
        {"file_name": "heimdall-1-0.png", "card_name": "Heimdall 1.0"},
        {"file_name": "heimdall-2-0.png", "card_name": "Heimdall 2.0"},
        {"file_name": "heinlein-grid.png", "card_name": "Heinlein Grid"},
        {"file_name": "helium-3-deposit.png", "card_name": "Helium-3 Deposit"},
        {"file_name": "hellion-alpha-test.png", "card_name": "Hellion Alpha Test"},
        {"file_name": "hemorrhage.png", "card_name": "Hemorrhage"},
        {"file_name": "high-risk-investment.png", "card_name": "High-Risk Investment"},
        {"file_name": "himitsu-bako.png", "card_name": "Himitsu-Bako"},
        {"file_name": "hive.png", "card_name": "Hive"},
        {"file_name": "hivemind.png", "card_name": "Hivemind"},
        {"file_name": "hokusai-grid.png", "card_name": "Hokusai Grid"},
        {"file_name": "hostage.png", "card_name": "Hostage"},
        {"file_name": "hostile-infrastructure.png", "card_name": "Hostile Infrastructure"},
        {"file_name": "hostile-takeover.png", "card_name": "Hostile Takeover"},
        {"file_name": "hourglass.png", "card_name": "Hourglass"},
        {"file_name": "house-of-knives.png", "card_name": "House of Knives"},
        {"file_name": "housekeeping.png", "card_name": "Housekeeping"},
        {"file_name": "howler.png", "card_name": "Howler"},
        {"file_name": "hq-interface.png", "card_name": "HQ Interface"},
        {"file_name": "hudson-1-0.png", "card_name": "Hudson 1.0"},
        {"file_name": "human-first.png", "card_name": "Human First"},
        {"file_name": "hunter.png", "card_name": "Hunter"},
        {"file_name": "ian-stirling-retired-spook.png", "card_name": "Iain Stirling: Retired Spook"},
        {"file_name": "ice-analyzer.png", "card_name": "Ice Analyzer"},
        {"file_name": "ice-carver.png", "card_name": "Ice Carver"},
        {"file_name": "ice-wall.png", "card_name": "Ice Wall"},
        {"file_name": "ichi-1-0.png", "card_name": "Ichi 1.0"},
        {"file_name": "ichi-2-0.png", "card_name": "Ichi 2.0"},
        {"file_name": "imp.png", "card_name": "Imp"},
        {"file_name": "inazuma.png", "card_name": "Inazuma"},
        {"file_name": "incubator.png", "card_name": "Incubator"},
        {"file_name": "indexing.png", "card_name": "Indexing"},
        {"file_name": "infiltration.png", "card_name": "Infiltration"},
        {"file_name": "information-overload.png", "card_name": "Information Overload"},
        {"file_name": "inject.png", "card_name": "Inject"},
        {"file_name": "inside-job.png", "card_name": "Inside Job"},
        {"file_name": "inside-man.png", "card_name": "Inside Man"},
        {"file_name": "interns.png", "card_name": "Interns"},
        {"file_name": "inti.png", "card_name": "Inti"},
        {"file_name": "invasion-of-privacy.png", "card_name": "Invasion of Privacy"},
        {"file_name": "investigative-journalism.png", "card_name": "Investigative Journalism"},
        {"file_name": "ireress.png", "card_name": "Ireress"},
        {"file_name": "isabel-mcguire.png", "card_name": "Isabel McGuire"},
        {"file_name": "it-department.png", "card_name": "IT Department"},
        {"file_name": "itenerant-protestors.png", "card_name": "Itinerant Protesters"},
        {"file_name": "ive-had-worse.png", "card_name": "I've Had Worse"},
        {"file_name": "ixodidae.png", "card_name": "Ixodidae"},
        {"file_name": "jackson-howard.png", "card_name": "Jackson Howard"},
        {"file_name": "janus-1-0.png", "card_name": "Janus 1.0"},
        {"file_name": "jinteki-replicating-perfection.png", "card_name": "Jinteki: Replicating Perfection"},
        {"file_name": "jinteki.png", "card_name": "Inti"},
        {"file_name": "john-masanori.png", "card_name": "John Masanori"},
        {"file_name": "joshua-b.png", "card_name": "Joshua B."},
        {"file_name": "kati-jones.png", "card_name": "Kati Jones"},
        {"file_name": "ken-express-tenma-disappeared-clone.png", "card_name": "Ken 'Express' Tenma: Disappeared Clone"},
        {"file_name": "keyhole.png", "card_name": "Keyhole"},
        {"file_name": "kitsune.png", "card_name": "Kitsune"},
        {"file_name": "knifed.png", "card_name": "Knifed"},
        {"file_name": "knight.png", "card_name": "Knight"},
        {"file_name": "komainu.png", "card_name": "Komainu"},
        {"file_name": "kraken.png", "card_name": "Kraken"},
        {"file_name": "labyrinthine-servers.png", "card_name": "Labyrinthine Servers"},
        {"file_name": "lag-time.png", "card_name": "Lag Time"},
        {"file_name": "lamprey.png", "card_name": "Lamprey"},
        {"file_name": "lancelot.png", "card_name": "Lancelot"},
        {"file_name": "lawyer-up.png", "card_name": "Lawyer Up"},
        {"file_name": "legwork.png", "card_name": "Legwork"},
        {"file_name": "lemuria-codecracker.png", "card_name": "Lemuria Codecracker"},
        {"file_name": "leprechaun.png", "card_name": "Leprechaun"},
        {"file_name": "leverage.png", "card_name": "Leverage"},
        {"file_name": "leviathan.png", "card_name": "Leviathan"},
        {"file_name": "levy-ar-lab-access.png", "card_name": "Levy AR Lab Access"},
        {"file_name": "levy-university.png", "card_name": "Levy University"},
        {"file_name": "liberated-account.png", "card_name": "Liberated Account"},
        {"file_name": "license-acquisition.png", "card_name": "License Acquisition"},
        {"file_name": "llds-energy-regulator.png", "card_name": "LLDS Energy Regulator"},
        {"file_name": "llds-processor.png", "card_name": "LLDS Processor"},
        {"file_name": "lockpick.png", "card_name": "Lockpick"},
        {"file_name": "logos.png", "card_name": "Logos"},
        {"file_name": "lotus-field.png", "card_name": "Lotus Field"},
        {"file_name": "lucky-find.png", "card_name": "Lucky Find"},
        {"file_name": "lycan.png", "card_name": "Lycan"},
        {"file_name": "magnum-opus.png", "card_name": "Magnum Opus"},
        {"file_name": "mamba.png", "card_name": "Mamba"},
        {"file_name": "mandatory-upgrades.png", "card_name": "Mandatory Upgrades"},
        {"file_name": "manhunt.png", "card_name": "Manhunt"},
        {"file_name": "mark-yale.png", "card_name": "Mark Yale"},
        {"file_name": "marked-accounts.png", "card_name": "Marked Accounts"},
        {"file_name": "marker.png", "card_name": "Marker"},
        {"file_name": "market-research.png", "card_name": "Market Research"},
        {"file_name": "markus-1.png", "card_name": "Markus 1.0"},
        {"file_name": "mass-install.png", "card_name": "Mass Install"},
        {"file_name": "matrix-analyzer.png", "card_name": "Matrix Analyzer"},
        {"file_name": "medical-breakthrough.png", "card_name": "Medical Breakthrough"},
        {"file_name": "medical-research-fundraiser.png", "card_name": "Medical Research Fundraiser"},
        {"file_name": "medium.png", "card_name": "Medium"},
        {"file_name": "melange-mining-corp.png", "card_name": "Melange Mining Corp."},
        {"file_name": "memstrips.png", "card_name": "MemStrips"},
        {"file_name": "mental-health-clinic.png", "card_name": "Mental Health Clinic"},
        {"file_name": "merlin.png", "card_name": "Merlin"},
        {"file_name": "midori.png", "card_name": "Midori"},
        {"file_name": "midseason-replacements.png", "card_name": "Midseason Replacements"},
        {"file_name": "midway-station-grid.png", "card_name": "Midway Station Grid"},
        {"file_name": "mimic.png", "card_name": "Mimic"},
        {"file_name": "minelayer.png", "card_name": "Minelayer"},
        {"file_name": "modded.png", "card_name": "Modded"},
        {"file_name": "monolith.png", "card_name": "Monolith"},
        {"file_name": "morning-star.png", "card_name": "Morning Star"},
        {"file_name": "mother-goddess.png", "card_name": "Mother Goddess"},
        {"file_name": "motivation.png", "card_name": "Motivation"},
        {"file_name": "mr-li.png", "card_name": "Merlin"},
        {"file_name": "muckraker.png", "card_name": "Muckraker"},
        {"file_name": "muresh-bodysuit.png", "card_name": "Muresh Bodysuit"},
        {"file_name": "mushin-no-shin.png", "card_name": "Mushin No Shin"},
        {"file_name": "mutate.png", "card_name": "Mutate"},
        {"file_name": "napd-contract.png", "card_name": "NAPD Contract"},
        {"file_name": "nasir-meidan.png", "card_name": "Inside Man"},
        {"file_name": "nbn-the-world-is-yours.png", "card_name": "NBN: The World is Yours*"},
        {"file_name": "nebula.png", "card_name": "Nebula"},
        {"file_name": "neotokyo-grid.png", "card_name": "NeoTokyo Grid"},
        {"file_name": "nerve-agent.png", "card_name": "Nerve Agent"},
        {"file_name": "net-celebrity.png", "card_name": "Net Celebrity"},
        {"file_name": "net-police.png", "card_name": "Net Police"},
        {"file_name": "net-shield.png", "card_name": "Net Shield"},
        {"file_name": "networking.png", "card_name": "Networking"},
        {"file_name": "neural-katana.png", "card_name": "Neural Katana"},
        {"file_name": "new-angeles-city-hall.png", "card_name": "New Angeles City Hall"},
        {"file_name": "next-design-guarding-the-net.png", "card_name": "NEXT Design: Guarding the Net"},
        {"file_name": "ninja.png", "card_name": "Ninja"},
        {"file_name": "nisei-division-the-next-generation.png", "card_name": "Nisei Division: The Next Generation"},
        {"file_name": "noise.png", "card_name": "Diesel"},
        {"file_name": "notoriety.png", "card_name": "Notoriety"},
        {"file_name": "off-the-grid.png", "card_name": "Off the Grid"},
        {"file_name": "omega.png", "card_name": "Omega"},
        {"file_name": "omni-drive.png", "card_name": "Omni-Drive"},
        {"file_name": "oracle-may.png", "card_name": "Oracle May"},
        {"file_name": "order-of-sol.png", "card_name": "Order of Sol"},
        {"file_name": "origami.png", "card_name": "Origami"},
        {"file_name": "orion.png", "card_name": "Orion"},
        {"file_name": "overmind.png", "card_name": "Overmind"},
        {"file_name": "oversight-ai.png", "card_name": "Oversight AI"},
        {"file_name": "pad-campaign.png", "card_name": "Adonis Campaign"},
        {"file_name": "paintbrush.png", "card_name": "Paintbrush"},
        {"file_name": "panic-button.png", "card_name": "Panic Button"},
        {"file_name": "paper-tripping.png", "card_name": "Paper Tripping"},
        {"file_name": "paper-wall.png", "card_name": "Paper Wall"},
        {"file_name": "parasite.png", "card_name": "Parasite"},
        {"file_name": "paricia.png", "card_name": "Paricia"},
        {"file_name": "passport.png", "card_name": "Passport"},
        {"file_name": "patch.png", "card_name": "Patch"},
        {"file_name": "pawn.png", "card_name": "Pawn"},
        {"file_name": "paywall-implementation.png", "card_name": "Paywall Implementation"},
        {"file_name": "peacock.png", "card_name": "Peacock"},
        {"file_name": "personal-workshop.png", "card_name": "Personal Workshop"},
        {"file_name": "pheromones.png", "card_name": "Pheromones"},
        {"file_name": "philotic-entanglement.png", "card_name": "Philotic Entanglement"},
        {"file_name": "pipeline.png", "card_name": "Pipeline"},
        {"file_name": "planned-assault.png", "card_name": "Planned Assault"},
        {"file_name": "plascrete-carapace.png", "card_name": "Plascrete Carapace"},
        {"file_name": "pop-up-window.png", "card_name": "Pop-up Window"},
        {"file_name": "port-anson-grid.png", "card_name": "Port Anson Grid"},
        {"file_name": "posted-bounty.png", "card_name": "Posted Bounty"},
        {"file_name": "power-grid-overload.png", "card_name": "Power Grid Overload"},
        {"file_name": "power-nap.png", "card_name": "Power Nap"},
        {"file_name": "power-shutdown.png", "card_name": "Power Shutdown"},
        {"file_name": "power-tap.png", "card_name": "Power Nap"},
        {"file_name": "precognition.png", "card_name": "Precognition"},
        {"file_name": "prepaid-voicepad.png", "card_name": "Prepaid VoicePAD"},
        {"file_name": "primary-transmission-dish.png", "card_name": "Primary Transmission Dish"},
        {"file_name": "priority-requisition.png", "card_name": "Priority Requisition"},
        {"file_name": "private-contracts.png", "card_name": "Private Contracts"},
        {"file_name": "private-security-force.png", "card_name": "Private Security Force"},
        {"file_name": "professional-contacts.png", "card_name": "Professional Contacts"},
        {"file_name": "profiteering.png", "card_name": "Profiteering"},
        {"file_name": "progenitor.png", "card_name": "Progenitor"},
        {"file_name": "project-ares.png", "card_name": "Project Ares"},
        {"file_name": "project-atlas.png", "card_name": "Project Atlas"},
        {"file_name": "project-beale.png", "card_name": "Project Beale"},
        {"file_name": "project-junebug.png", "card_name": "Project Junebug"},
        {"file_name": "project-vitruvius.png", "card_name": "Project Vitruvius"},
        {"file_name": "project-wotan.png", "card_name": "Project Wotan"},
        {"file_name": "psychic-field.png", "card_name": "Psychic Field"},
        {"file_name": "psychographics.png", "card_name": "Psychographics"},
        {"file_name": "public-sympathy.png", "card_name": "Public Sympathy"},
        {"file_name": "public-terminal.png", "card_name": "Public Terminal"},
        {"file_name": "punitive-counterstrike.png", "card_name": "Punitive Counterstrike"},
        {"file_name": "pup.png", "card_name": "Pup"},
        {"file_name": "push-your-luck.png", "card_name": "Push Your Luck"},
        {"file_name": "q-coherence-chip.png", "card_name": "Q-Coherence Chip"},
        {"file_name": "qianju-pt.png", "card_name": "Qianju PT"},
        {"file_name": "quality-time.png", "card_name": "Quality Time"},
        {"file_name": "quandary.png", "card_name": "Quandary"},
        {"file_name": "queens-gambit.png", "card_name": "Queen's Gambit"},
        {"file_name": "quest-completed.png", "card_name": "Quest Completed"},
        {"file_name": "quetzal.png", "card_name": "Fetal AI"},
        {"file_name": "r-d-interface.png", "card_name": "Archives Interface"},
        {"file_name": "rabbit-hole.png", "card_name": "Rabbit Hole"},
        {"file_name": "rachel-beckman.png", "card_name": "Rachel Beckman"},
        {"file_name": "rainbow.png", "card_name": "Rainbow"},
        {"file_name": "raymond-flint.png", "card_name": "Raymond Flint"},
        {"file_name": "reclamation-order.png", "card_name": "Reclamation Order"},
        {"file_name": "recon.png", "card_name": "Recon"},
        {"file_name": "record-reconstructor.png", "card_name": "Record Reconstructor"},
        {"file_name": "red-herrings.png", "card_name": "Red Herrings"},
        {"file_name": "refractor.png", "card_name": "Refractor"},
        {"file_name": "reina-roja-freedom-fighter.png", "card_name": "Reina Roja: Freedom Fighter"},
        {"file_name": "replicator.png", "card_name": "Replicator"},
        {"file_name": "research-station.png", "card_name": "Research Station"},
        {"file_name": "restoring-face.png", "card_name": "Restoring Face"},
        {"file_name": "restructure.png", "card_name": "Restructure"},
        {"file_name": "restructured-datapool.png", "card_name": "Restructured Datapool"},
        {"file_name": "retrieval-run.png", "card_name": "Retrieval Run"},
        {"file_name": "reuse.png", "card_name": "Reuse"},
        {"file_name": "reversed-accounts.png", "card_name": "Reversed Accounts"},
        {"file_name": "rework.png", "card_name": "Rework"},
        {"file_name": "rex-campaign.png", "card_name": "Rex Campaign"},
        {"file_name": "rielle-kit-peddler-transhuman.png", "card_name": "Rielle 'Kit' Peddler: Transhuman"},
        {"file_name": "ronin.png", "card_name": "Ronin"},
        {"file_name": "rook.png", "card_name": "Rook"},
        {"file_name": "rototurret.png", "card_name": "Rototurret"},
        {"file_name": "ruhr-valley.png", "card_name": "Ruhr Valley"},
        {"file_name": "running-interference.png", "card_name": "Running Interference"},
        {"file_name": "sacrificial-clone.png", "card_name": "Sacrificial Clone"},
        {"file_name": "sacrificial-construct.png", "card_name": "Sacrificial Construct"},
        {"file_name": "sage.png", "card_name": "Sage"},
        {"file_name": "sagitarius.png", "card_name": "Sagittarius"},
        {"file_name": "sahasrara.png", "card_name": "Sahasrara"},
        {"file_name": "salvage.png", "card_name": "Salvage"},
        {"file_name": "same-old-thing.png", "card_name": "Same Old Thing"},
        {"file_name": "sansan-city-grid.png", "card_name": "SanSan City Grid"},
        {"file_name": "satellite-grid.png", "card_name": "Satellite Grid"},
        {"file_name": "satellite-uplink.png", "card_name": "Satellite Uplink"},
        {"file_name": "savoir-faire.png", "card_name": "Savoir-faire"},
        {"file_name": "scavenge.png", "card_name": "Scavenge"},
        {"file_name": "scheherazade.png", "card_name": "Scheherazade"},
        {"file_name": "scorched-earth.png", "card_name": "Scorched Earth"},
        {"file_name": "scrubbed.png", "card_name": "Scrubbed"},
        {"file_name": "scrubber.png", "card_name": "Scrubber"},
        {"file_name": "sea-source.png", "card_name": "The Source"},
        {"file_name": "sealed-vault.png", "card_name": "Sealed Vault"},
        {"file_name": "searchlight.png", "card_name": "Searchlight"},
        {"file_name": "security-subcontract.png", "card_name": "Security Subcontract"},
        {"file_name": "security-testing.png", "card_name": "Security Testing"},
        {"file_name": "self-destruct.png", "card_name": "Self-destruct"},
        {"file_name": "self-modifying-code.png", "card_name": "Self-modifying Code"},
        {"file_name": "sensei.png", "card_name": "Sensei"},
        {"file_name": "sentinel-defense-program.png", "card_name": "Sentinel Defense Program"},
        {"file_name": "server-diagnostics.png", "card_name": "Server Diagnostics"},
        {"file_name": "shadow.png", "card_name": "Shadow"},
        {"file_name": "sharpshooter.png", "card_name": "Sharpshooter"},
        {"file_name": "shattered-remains.png", "card_name": "Shattered Remains"},
        {"file_name": "shell-corporation.png", "card_name": "Shell Corporation"},
        {"file_name": "sherlock-1-0.png", "card_name": "Sherlock 1.0"},
        {"file_name": "shi-kyu.png", "card_name": "Ashigaru"},
        {"file_name": "shinobi.png", "card_name": "Shinobi"},
        {"file_name": "shipment-from-kaguya.png", "card_name": "Shipment from Kaguya"},
        {"file_name": "shipment-from-mirrormorph.png", "card_name": "Shipment from MirrorMorph"},
        {"file_name": "shipment-from-sansan.png", "card_name": "Shipment from SanSan"},
        {"file_name": "shiro.png", "card_name": "Shiro"},
        {"file_name": "shock.png", "card_name": "Shock!"},
        {"file_name": "shoot-the-moon.png", "card_name": "Shoot the Moon"},
        {"file_name": "showing-off.png", "card_name": "Showing Off"},
        {"file_name": "silencer.png", "card_name": "Silencer"},
        {"file_name": "silhouette-stealth-operative.png", "card_name": "Silhouette: Stealth Operative"},
        {"file_name": "simone-diego.png", "card_name": "Simone Diego"},
        {"file_name": "singularity.png", "card_name": "Singularity"},
        {"file_name": "snare.png", "card_name": "Snare!"},
        {"file_name": "snatch-and-grab.png", "card_name": "Snatch and Grab"},
        {"file_name": "sneakdoor-beta.png", "card_name": "Sneakdoor Beta"},
        {"file_name": "snitch.png", "card_name": "Snitch"},
        {"file_name": "snoop.png", "card_name": "Snoop"},
        {"file_name": "snowball.png", "card_name": "Snowball"},
        {"file_name": "snowflake.png", "card_name": "Snowflake"},
        {"file_name": "social-engineering.png", "card_name": "Social Engineering"},
        {"file_name": "space-camp.png", "card_name": "Space Camp"},
        {"file_name": "special-orde.png", "card_name": "Special Order"},
        {"file_name": "spinal-modem.png", "card_name": "Spinal Modem"},
        {"file_name": "spooned.png", "card_name": "Spooned"},
        {"file_name": "starlight-crusade-funding.png", "card_name": "Starlight Crusade Funding"},
        {"file_name": "stim-dealer.png", "card_name": "Stim Dealer"},
        {"file_name": "stimhack.png", "card_name": "Stimhack"},
        {"file_name": "strongbox.png", "card_name": "Strongbox"},
        {"file_name": "sub-boost.png", "card_name": "Sub Boost"},
        {"file_name": "subliminal-messaging.png", "card_name": "Subliminal Messaging"},
        {"file_name": "successful-demonstration.png", "card_name": "Successful Demonstration"},
        {"file_name": "sundew.png", "card_name": "Sundew"},
        {"file_name": "sunset.png", "card_name": "Sunset"},
        {"file_name": "superioir-cyberwalls.png", "card_name": "Superior Cyberwalls"},
        {"file_name": "sure-gamble.png", "card_name": "Sure Gamble"},
        {"file_name": "surge.png", "card_name": "Surge"},
        {"file_name": "susanoo-no-mikoto.png", "card_name": "Susanoo-No-Mikoto"},
        {"file_name": "swarm.png", "card_name": "Swarm"},
        {"file_name": "sweeps-week.png", "card_name": "Sweeps Week"},
        {"file_name": "switchblade.png", "card_name": "Switchblade"},
        {"file_name": "swordsman.png", "card_name": "Swordsman"},
        {"file_name": "tallie-perrault.png", "card_name": "Tallie Perrault"},
        {"file_name": "targeted-marketing.png", "card_name": "Targeted Marketing"},
        {"file_name": "taurus.png", "card_name": "Taurus"},
        {"file_name": "tenma-line.png", "card_name": "Tenma Line"},
        {"file_name": "tennin-institute-the-secrets-within.png", "card_name": "Tennin Institute: The Secrets Within"},
        {"file_name": "test-run.png", "card_name": "Test Run"},
        {"file_name": "the-board.png", "card_name": "The Board"},
        {"file_name": "the-cleaners.png", "card_name": "The Cleaners"},
        {"file_name": "the-future-perfect.png", "card_name": "The Future Perfect"},
        {"file_name": "the-helpful-ai.png", "card_name": "The Helpful AI"},
        {"file_name": "the-makers-eye.png", "card_name": "The Maker's Eye"},
        {"file_name": "the-news-now-hour.png", "card_name": "The News Now Hour"},
        {"file_name": "the-personal-touch.png", "card_name": "The Personal Touch"},
        {"file_name": "the-professor-keeper-of-knowledge.png", "card_name": "The Professor: Keeper of Knowledge"},
        {"file_name": "the-root.png", "card_name": "The Root"},
        {"file_name": "the-supplier.png", "card_name": "The Supplier"},
        {"file_name": "the-toolbox.png", "card_name": "The Toolbox"},
        {"file_name": "the-twins.png", "card_name": "The Twins"},
        {"file_name": "theophilius-bagbiter.png", "card_name": "Theophilius Bagbiter"},
        {"file_name": "thomas-haas.png", "card_name": "Thomas Haas"},
        {"file_name": "three-steps-ahead.png", "card_name": "Three Steps Ahead"},
        {"file_name": "tinkering.png", "card_name": "Tinkering"},
        {"file_name": "tmi.png", "card_name": "Inti"},
        {"file_name": "tollbooth.png", "card_name": "Tollbooth"},
        {"file_name": "torch.png", "card_name": "Torch"},
        {"file_name": "tori-hanzo.png", "card_name": "Tori Hanzō"},
        {"file_name": "toshiyuki-sakai.png", "card_name": "Toshiyuki Sakai"},
        {"file_name": "trade-in.png", "card_name": "Trade-In"},
        {"file_name": "traffic-accident.png", "card_name": "Traffic Accident"},
        {"file_name": "tri-maf-contact.png", "card_name": "Tri-maf Contact"},
        {"file_name": "trick-of-light.png", "card_name": "Trick of Light"},
        {"file_name": "troll.png", "card_name": "Troll"},
        {"file_name": "tsurugi.png", "card_name": "Tsurugi"},
        {"file_name": "turtlebacks.png", "card_name": "Turtlebacks"},
        {"file_name": "tyrant.png", "card_name": "Tyrant"},
        {"file_name": "tyrs-hand.png", "card_name": "Tyr's Hand"},
        {"file_name": "underworld-contact.png", "card_name": "Underworld Contact"},
        {"file_name": "uninstall.png", "card_name": "Uninstall"},
        {"file_name": "universal-connectivity-fee.png", "card_name": "Universal Connectivity Fee"},
        {"file_name": "unorthodox-predictions.png", "card_name": "Unorthodox Predictions"},
        {"file_name": "unregistered-s-w-35.png", "card_name": "Unregistered S&W '35"},
        {"file_name": "unscheduled-maintenance.png", "card_name": "Unscheduled Maintenance"},
        {"file_name": "uroboros.png", "card_name": "Uroboros"},
        {"file_name": "utopia-fragment.png", "card_name": "Utopia Fragment"},
        {"file_name": "utopia-shard.png", "card_name": "Utopia Shard"},
        {"file_name": "vamp.png", "card_name": "Vamp"},
        {"file_name": "verberus-cujo-h3.png", "card_name": "Cerberus 'Cuj.0' H3"},
        {"file_name": "veterans-program.png", "card_name": "Veterans Program"},
        {"file_name": "vigil.png", "card_name": "Vigil"},
        {"file_name": "viktor-1-0.png", "card_name": "Viktor 1.0"},
        {"file_name": "viktor-2-0.png", "card_name": "Viktor 2.0"},
        {"file_name": "viper.png", "card_name": "Viper"},
        {"file_name": "virgo.png", "card_name": "Virgo"},
        {"file_name": "virus-breeding-ground.png", "card_name": "Virus Breeding Ground"},
        {"file_name": "vulcan-coverup.png", "card_name": "Vulcan Coverup"},
        {"file_name": "wall-of-static.png", "card_name": "Wall of Static"},
        {"file_name": "wall-of-thorns.png", "card_name": "Wall of Thorns"},
        {"file_name": "wanton-destruction.png", "card_name": "Wanton Destruction"},
        {"file_name": "wendigo.png", "card_name": "Wendigo"},
        {"file_name": "weyland-consortium-because-we-built-it.png", "card_name": "Weyland Consortium: Because We Built It"},
        {"file_name": "weyland-consortium.png", "card_name": "Weyland Consortium: Because We Built It"},
        {"file_name": "whirlpool.png", "card_name": "Whirlpool"},
        {"file_name": "will-o-the-wisp.png", "card_name": "Will-o'-the-Wisp"},
        {"file_name": "window.png", "card_name": "Window"},
        {"file_name": "witness-tampering.png", "card_name": "Witness Tampering"},
        {"file_name": "woman-in-the-red-dress.png", "card_name": "Woman in the Red Dress"},
        {"file_name": "woodcutter.png", "card_name": "Woodcutter"},
        {"file_name": "wormhole.png", "card_name": "Wormhole"},
        {"file_name": "wotan.png", "card_name": "Wotan"},
        {"file_name": "wraparound.png", "card_name": "Wraparound"},
        {"file_name": "wyldside.png", "card_name": "Wyldside"},
        {"file_name": "wyrm.png", "card_name": "Wyrm"},
        {"file_name": "xanadu.png", "card_name": "Xanadu"},
        {"file_name": "yagura.png", "card_name": "Yagura"},
        {"file_name": "yog-0.png", "card_name": "Yog.0"},
        {"file_name": "zaibatsu-loyalty.png", "card_name": "Zaibatsu Loyalty"},
        {"file_name": "zed-1-0.png", "card_name": "Zed 1.0"},
        {"file_name": "zona-sul-shipping.png", "card_name": "Zona Sul Shipping"},
        {"file_name": "zu-13-key-master.png", "card_name": "ZU.13 Key Master"}
    ])


def downgrade():
    pass
